### ISSUE TITLE
No longer indicating errors

### ISSUE THREAD

**Issue by 33mhz** [lukasz-duda/ErrorIndicator#13] opened 2023-08-15 12:43 UTC
I'm not sure when this started, but I can't get it to indicate errors on the page anymore. The addon "detected 0 errors".

I don't have any of the `Ignore` fields checked. There are console errors, 404 http responses, typing "what" into console.

Firefox 116.0.2

**Comment by lukasz-duda** [comment] 2023-08-20 19:04
Hi 33mhz,
I think I can see it. Sometimes the error is displayed, but most of the time it's ignored. I'll try to find out the reason and let you know.
Please be patient ;-)

![obraz](https://github.com/lukasz-duda/ErrorIndicator/assets/2528831/3d2a28bc-be51-4c2e-810e-8dd33d8ea1c2)

![obraz](https://github.com/lukasz-duda/ErrorIndicator/assets/2528831/7fbd860d-a736-4c11-8309-a876deb3e532)

**Comment by 33mhz** [comment] 2023-08-21 14:45
Sweet, thanks.

**Comment by lukasz-duda** [comment] 2023-08-29 20:11
Finally I've found an hour to see what's going on.
When Firefox notifies about completed web request it sometimes doesn't assign it to the correct tab.
![obraz](https://github.com/lukasz-duda/ErrorIndicator/assets/2528831/93b63950-bfe3-4842-9a38-e59d4804d77f)
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onCompleted#details_2

I am thinking about two solutions:
1. I can try register the Firefox issue and see if Mozilla can help.
2. If web error was not assigned to the any tab I can show it on each tab. It could be confusing.

**Comment by 33mhz** [comment] 2023-08-29 20:33
Thanks. It does seem ideal to open an issue, even if it's ignored...

You're saying it would effectively become window-wide error reporting instead of tab-specific? I think that's a more useful default for me, at least.

**Comment by lukasz-duda** [comment] 2023-08-30 08:20
Yes, until version 1.7 error indicator did not support tabs and reported all errors. I separated the tabs because someone reported the need. Do you say that you would prefer to present all errors in the report regardless of the active tab? Maybe I should add new setting to allow personal choice.

**Comment by 33mhz** [comment] 2023-08-30 12:29
Sounds good to me.

**Comment by lukasz-duda** [comment] 2023-09-06 14:12
Can you try new option to report errors from any tab?
It can be used as a workaround until Firefox corrects tab identifier provided in completed web request.
![image](https://github.com/lukasz-duda/ErrorIndicator/assets/2528831/9193c07d-b5fb-4e00-8645-70d8067a54ad)

**Comment by lukasz-duda** [comment] 2023-09-06 14:49
The Firefox bug was already reported and fixed in version 58.
https://bugzilla.mozilla.org/show_bug.cgi?id=1425216
I'll add another issue for version 117.

**Comment by 33mhz** [comment] 2023-09-07 13:06
Hm, I have the option and set it to "all errors", but typing "what" into console shows an error in console but not in the addon.

**Comment by lukasz-duda** [comment] 2023-09-07 13:51
That's because the plugin was designed to indicate errors from 3 sources regarding open page:
- console.error('message') sent from that page https://developer.mozilla.org/en-US/docs/Web/API/console/error
- window error event fired from that page https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event
- completed web request in context of loaded page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onCompleted

It wasn't designed to show errors from context other than loaded page, for example from browser console or from another web extension.

**Comment by 33mhz** [comment] 2023-09-07 13:55
Got it. I am getting errors now, after testing more thoroughly. :) Thanks!

**Comment by lukasz-duda** [comment] 2023-09-07 14:14
Thanks for you feedback!
I'll let you know when I get an update about that Firefox issue.

**Closed as completed by lukasz-duda** 2023-09-07 14:14 UTC
